// Bunch of example leads to seed the database with
export const LEAD = [
  {
    referredByEmail: "penny.saver@benefit.demo",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@gmail.com",
    phone: "123-456-789",
    serviceOfInterest: "not sure",
    status: "during",
  },
  {
    referredByEmail: "penny.saver@benefit.demo",
    firstName: "Anna",
    lastName: "Smith",
    email: "anna.smith@gmail.com",
    phone: "234-567-890",
    serviceOfInterest: "subsidies",
    status: "accepted",
  },
  {
    referredByEmail: "penny.saver@benefit.demo",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@gmail.com",
    phone: "345-678-901",
    serviceOfInterest: "credits",
    status: "during",
  },
  {
    referredByEmail: "penny.saver@benefit.demo",
    firstName: "Emily",
    lastName: "Brown",
    email: "emily.brown@gmail.com",
    phone: "456-789-012",
    serviceOfInterest: "insurance",
    status: "rejected",
  },
  {
    referredByEmail: "penny.saver@benefit.demo",
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@gmail.com",
    phone: "567-890-123",
    serviceOfInterest: "subsidies",
    status: "during",
  },
  {
    referredByEmail: "penny.saver@benefit.demo",
    firstName: "Sophia",
    lastName: "Taylor",
    email: "sophia.taylor@gmail.com",
    phone: "678-901-234",
    serviceOfInterest: "credits",
    status: "accepted",
  },
  {
    referredByEmail: "penny.saver@benefit.demo",
    firstName: "Daniel",
    lastName: "Anderson",
    email: "daniel.anderson@gmail.com",
    phone: "789-012-345",
    serviceOfInterest: "insurance",
    status: "during",
  },
  {
    referredByEmail: "penny.saver@benefit.demo",
    firstName: "Olivia",
    lastName: "Martinez",
    email: "olivia.martinez@gmail.com",
    phone: "890-123-456",
    serviceOfInterest: "not sure",
    status: "accepted",
  },
  {
    referredByEmail: "penny.saver@benefit.demo",
    firstName: "James",
    lastName: "Thomas",
    email: "james.thomas@gmail.com",
    phone: "901-234-567",
    serviceOfInterest: "credits",
    status: "rejected",
  },
  {
    referredByEmail: "penny.saver@benefit.demo",
    firstName: "Isabella",
    lastName: "White",
    email: "isabella.white@gmail.com",
    phone: "012-345-678",
    serviceOfInterest: "subsidies",
    status: "during",
  },
] as const;
